export declare const DEFAULT_LONG_PRESS_DELAY = 350;
export declare const MESSAGE_SEARCH_SAFE_SCROLL_DELAY = 500;
export declare const MESSAGE_FOCUS_ANIMATION_DELAY = 250;
export declare const UNKNOWN_USER_ID = "##__USER_ID_IS_NOT_PROVIDED__##";
export declare const VOICE_MESSAGE_META_ARRAY_DURATION_KEY = "KEY_VOICE_MESSAGE_DURATION";
export declare const VOICE_MESSAGE_META_ARRAY_MESSAGE_TYPE_KEY = "KEY_INTERNAL_MESSAGE_TYPE";
