"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.VOICE_MESSAGE_META_ARRAY_MESSAGE_TYPE_KEY = exports.VOICE_MESSAGE_META_ARRAY_DURATION_KEY = exports.UNKNOWN_USER_ID = exports.MESSAGE_SEARCH_SAFE_SCROLL_DELAY = exports.MESSAGE_FOCUS_ANIMATION_DELAY = exports.DEFAULT_LONG_PRESS_DELAY = void 0;
const DEFAULT_LONG_PRESS_DELAY = 350;
exports.DEFAULT_LONG_PRESS_DELAY = DEFAULT_LONG_PRESS_DELAY;
const MESSAGE_SEARCH_SAFE_SCROLL_DELAY = 500;
exports.MESSAGE_SEARCH_SAFE_SCROLL_DELAY = MESSAGE_SEARCH_SAFE_SCROLL_DELAY;
const MESSAGE_FOCUS_ANIMATION_DELAY = 250;
exports.MESSAGE_FOCUS_ANIMATION_DELAY = MESSAGE_FOCUS_ANIMATION_DELAY;
const UNKNOWN_USER_ID = '##__USER_ID_IS_NOT_PROVIDED__##';
exports.UNKNOWN_USER_ID = UNKNOWN_USER_ID;
const VOICE_MESSAGE_META_ARRAY_DURATION_KEY = 'KEY_VOICE_MESSAGE_DURATION';
exports.VOICE_MESSAGE_META_ARRAY_DURATION_KEY = VOICE_MESSAGE_META_ARRAY_DURATION_KEY;
const VOICE_MESSAGE_META_ARRAY_MESSAGE_TYPE_KEY = 'KEY_INTERNAL_MESSAGE_TYPE';
exports.VOICE_MESSAGE_META_ARRAY_MESSAGE_TYPE_KEY = VOICE_MESSAGE_META_ARRAY_MESSAGE_TYPE_KEY;
//# sourceMappingURL=constants.js.map